# Generated by Django 2.2.16 on 2020-09-25 21:56

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('text', markdownx.models.MarkdownxField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='file')),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('home', models.BooleanField(default=False, help_text='Display entry in home page.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name_parent', models.ForeignKey(blank=True, help_text="Use this parent's name as prefix when displayed out of context.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_using_name', to='core.Entry')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='EntryParentThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_through', to='core.Entry')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_through', to='core.Entry')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='core.EntryParentThroughModel', to='core.Entry'),
        ),
    ]
