# Generated by Django 2.2.16 on 2020-09-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_aka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name_parent',
        ),
        migrations.AddField(
            model_name='entry',
            name='name_prefix',
            field=models.ForeignKey(blank=True, help_text="Use this parent/tag entry's name as prefix when displayed out of context.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_using_name', to='core.Entry', verbose_name='Entry name prefix'),
        ),
    ]
