# Generated by Django 2.2.16 on 2020-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200928_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryparentthroughmodel',
            name='next_auto',
            field=models.BooleanField(default=False),
        ),
    ]
